<?php

$labels = array();
$labels['buttonText'] = 'Archiv';
$labels['buttonTitle'] = 'Diese Mail archivieren';
$labels['archived'] = 'Erfolgreich archiviert';
$labels['archiveFolder'] = 'Archiv';
$labels['archiveType'] = 'Archiviere nach...';
$labels['archiveTypeYear'] = 'Jahr';
$labels['archiveTypeMonth'] = 'Monat';
$labels['archiveTypeSender'] = 'Absender';
$labels['errorMessage'] = '<b>Fehler:</b> Konnte E-Mail(s) nicht archivieren.';
$labels['errorMessageTitle'] = 'Fehler';
$labels['unknownSender'] = 'Unbekannter Absender';
$labels['archive'] = 'Archiv';

?>
