<?php

$labels = array();
$labels['buttonText'] = 'Archive';
$labels['buttonTitle'] = 'Archive this message';
$labels['archived'] = 'Successfully archived';
$labels['archiveFolder'] = 'Archive';
$labels['archiveType'] = 'Archive by...';
$labels['archiveTypeYear'] = 'Year';
$labels['archiveTypeMonth'] = 'Month';
$labels['archiveTypeSender'] = 'Sender';
$labels['errorMessage'] = '<b>Error:</b> Failed to move messages.';
$labels['errorMessageTitle'] = 'Error';
$labels['unknownSender'] = 'Unknown Sender';
$labels['archive'] = 'Archive';

?>
