<?php

$labels = array();
$labels['buttonText'] = 'Archief';
$labels['buttonTitle'] = 'Archiveer dit bericht';
$labels['archived'] = 'Gearchiveerd';
$labels['archiveFolder'] = 'Archief';
$labels['archiveType'] = 'Archiveer per...';
$labels['archiveTypeYear'] = 'Jaar';
$labels['archiveTypeMonth'] = 'Maand';
$labels['archiveTypeSender'] = 'Afzender';
$labels['errorMessage'] = '<b>Fout:</b> Kan bericht niet verplaatsen.';
$labels['errorMessageTitle'] = 'Fout';
$labels['unknownSender'] = 'Onbekende afzender';
$labels['archive'] = 'Archief';

?>
