<?php

$labels = array();
$labels['buttonText'] = 'Arkivera';
$labels['buttonTitle'] = 'Arkivera meddelandet';
$labels['archived'] = 'Brev arkiverat';
$labels['archiveFolder'] = 'Arkiv';
$labels['archiveType'] = 'Arkivera med...';
$labels['archiveTypeYear'] = 'År';
$labels['archiveTypeMonth'] = 'Månad';
$labels['archiveTypeSender'] = 'Avsändare';
$labels['errorMessage'] = '<b>Fel:</b> Kunde inte flytta brevet.';
$labels['errorMessageTitle'] = 'Fel';
$labels['unknownSender'] = 'Okänd avsändare';
$labels['archive'] = 'Arkiv';

